/**
 * Static list of all Pokémon TCG sets
 * 
 * This is hardcoded to avoid expensive GROUP BY queries on the cards table in Turso DB.
 * Update this when new sets are released (typically 3-4 times per year).
 * 
 * Last updated: 2026-04-11
 */

// Record of set code -> set name for O(1) lookups
export const SETS: Record<string, string> = {
  "AOR": "Ancient Origins",
  "AQ": "Aquapolis",
  "AR": "Arceus",
  "ASC": "Ascended Heroes",
  "ASR": "Astral Radiance",
  "BKP": "BREAKpoint",
  "BKT": "BREAKthrough",
  "BS": "Base Set",
  "B2": "Base Set 2",
  "BST": "Battle Styles",
  "BLW": "Black & White",
  "BWP": "Black & White Promos",
  "TK5E": "Black & White Trainer Kit (Excadrill)",
  "BLK": "Black Bolt",
  "BCR": "Boundaries Crossed",
  "BRS": "Brilliant Stars",
  "BUS": "Burning Shadows",
  "CL": "Call of Legends",
  "CEL": "Celebrations",
  "CES": "Celestial Storm",
  "CPA": "Champion's Path",
  "CRE": "Chilling Reign",
  "CEC": "Cosmic Eclipse",
  "CIN": "Crimson Invasion",
  "CRZ": "Crown Zenith",
  "CG": "Crystal Guardians",
  "DEX": "Dark Explorers",
  "DAA": "Darkness Ablaze",
  "DS": "Delta Species",
  "DX": "Deoxys",
  "DRI": "Destined Rivals",
  "DET": "Detective Pikachu",
  "DP": "Diamond & Pearl",
  "TK3L": "Diamond & Pearl Trainer Kit (Lucario)",
  "TK3M": "Diamond & Pearl Trainer Kit (Manaphy)",
  "DCR": "Double Crisis",
  "DR": "Dragon",
  "DF": "Dragon Frontiers",
  "DRM": "Dragon Majesty",
  "DRV": "Dragon Vault",
  "DRX": "Dragons Exalted",
  "TK1A": "EX Trainer Kit (Latias)",
  "TK1O": "EX Trainer Kit (Latios)",
  "TK2M": "EX Trainer Kit (Minun)",
  "TK2P": "EX Trainer Kit (Plusle)",
  "EM": "Emerald",
  "EPO": "Emerging Powers",
  "EVO": "Evolutions",
  "EVS": "Evolving Skies",
  "EX": "Expedition",
  "FCO": "Fates Collide",
  "RG": "FireRed & LeafGreen",
  "FLF": "Flashfire",
  "FLI": "Forbidden Light",
  "FO": "Fossil",
  "FFI": "Furious Fists",
  "FST": "Fusion Strike",
  "GEN": "Generations",
  "GE": "Great Encounters",
  "GRI": "Guardians Rising",
  "G2": "Gym Challenge",
  "G1": "Gym Heroes",
  "TK4G": "HS Trainer Kit (Gyarados)",
  "TK4R": "HS Trainer Kit (Raichu)",
  "HS": "HeartGold & SoulSilver",
  "HIF": "Hidden Fates",
  "HL": "Hidden Legends",
  "HP": "Holon Phantoms",
  "JTG": "Journey Together",
  "JU": "Jungle",
  "KSS": "Kalos Starter Set",
  "LM": "Legend Maker",
  "LC": "Legendary Collection",
  "LTR": "Legendary Treasures",
  "LA": "Legends Awakened",
  "LOR": "Lost Origin",
  "LOT": "Lost Thunder",
  "MD": "Majestic Dawn",
  "MCD11": "McDonald's Collection 2011",
  "MCD12": "McDonald's Collection 2012",
  "MCD16": "McDonald's Collection 2016",
  "MCD19": "McDonald's Collection 2019",
  "MCD21": "McDonald's Collection 2021",
  "MCD22": "McDonald's Collection 2022",
  "M23": "McDonald's Match Battle 2023",
  "MEG": "Mega Evolution",
  "MEE": "Mega Evolution Energy",
  "MEP": "Mega Evolution Promos",
  "MT": "Mysterious Treasures",
  "N4": "Neo Destiny",
  "N2": "Neo Discovery",
  "N1": "Neo Genesis",
  "N3": "Neo Revelation",
  "NXD": "Next Destinies",
  "NVI": "Noble Victories",
  "OBF": "Obsidian Flames",
  "P1": "POP Series 1",
  "P2": "POP Series 2",
  "P3": "POP Series 3",
  "P4": "POP Series 4",
  "P5": "POP Series 5",
  "P6": "POP Series 6",
  "P7": "POP Series 7",
  "P8": "POP Series 8",
  "P9": "POP Series 9",
  "PAL": "Paldea Evolved",
  "PAF": "Paldean Fates",
  "PAR": "Paradox Rift",
  "POR": "Perfect Order",
  "PFL": "Phantasmal Flames",
  "PHF": "Phantom Forces",
  "PLB": "Plasma Blast",
  "PLF": "Plasma Freeze",
  "PLS": "Plasma Storm",
  "PL": "Platinum",
  "MEW": "Pokémon 151",
  "FUT20": "Pokémon Futsal Promos 2020",
  "PGO": "Pokémon GO",
  "CLB": "Pokémon Trading Card Game Classic (Blastoise)",
  "CLC": "Pokémon Trading Card Game Classic (Charizard)",
  "CLV": "Pokémon Trading Card Game Classic (Venusaur)",
  "PK": "Power Keepers",
  "PRC": "Primal Clash",
  "PRE": "Prismatic Evolutions",
  "RO": "RO",
  "RCL": "Rebel Clash",
  "RR": "Rising Rivals",
  "ROS": "Roaring Skies",
  "RS": "Ruby & Sapphire",
  "RM": "Rumble",
  "SS": "Sandstorm",
  "SVI": "Scarlet & Violet",
  "SVE": "Scarlet & Violet Energy",
  "SVP": "Scarlet & Violet Promos",
  "SW": "Secret Wonders",
  "SHF": "Shining Fates",
  "SLG": "Shining Legends",
  "SFA": "Shrouded Fable",
  "SIT": "Silver Tempest",
  "SK": "Skyridge",
  "SI": "Southern Islands",
  "STS": "Steam Siege",
  "SCR": "Stellar Crown",
  "SF": "Stormfront",
  "SUM": "Sun & Moon",
  "SMP": "Sun & Moon Promos",
  "TK10A": "Sun & Moon Trainer Kit (Alolan Raichu)",
  "TK10L": "Sun & Moon Trainer Kit (Lycanroc)",
  "SV": "Supreme Victors",
  "SSP": "Surging Sparks",
  "SSH": "Sword & Shield",
  "TK5Z": "TK5Z",
  "MA": "Team Magma vs Team Aqua",
  "TR": "Team Rocket",
  "TEU": "Team Up",
  "TEF": "Temporal Forces",
  "TM": "Triumphant",
  "TWM": "Twilight Masquerade",
  "UPR": "Ultra Prism",
  "UNB": "Unbroken Bonds",
  "UD": "Undaunted",
  "UNM": "Unified Minds",
  "UL": "Unleashed",
  "UF": "Unseen Forces",
  "VIV": "Vivid Voltage",
  "WHT": "White Flare",
  "XY": "XY",
  "XYP": "XY Promos",
  "TK7A": "XY Trainer Kit (Bisharp)",
  "TK8A": "XY Trainer Kit (Latias)",
  "TK8O": "XY Trainer Kit (Latios)",
  "TK6N": "XY Trainer Kit (Noivern)",
  "TK9P": "XY Trainer Kit (Pikachu Libre)",
  "TK9S": "XY Trainer Kit (Suicune)",
  "TK6S": "XY Trainer Kit (Sylveon)",
  "TK7B": "XY Trainer Kit (Wigglytuff)"
}

// Get set name from code
export function getSetName(code: string): string {
  return SETS[code] || code
}

// Get all sets as array (for dropdown UI)
export function getAllSetsArray(): Array<{ code: string; name: string }> {
  return Object.entries(SETS).map(([code, name]) => ({ code, name }))
}
